import slugify from "slugify";
import hello,{cikart,helloname,topla,text,user,array_users} from "./mymodule.js";
import callback from "./callback";
// console.log("Hello Alper Node Js İle çağrılacagım  -- Terminalden node index.js");
// // var slugify=require('slugify');
// const title=slugify('alper oner  aslpda das das dasd asd as dsa  d     sadas');
// const title2=slugify('alper oner  aslpda das das dasd asd as dsa  d     sadas',"*");
// console.log(title +"\n");
// console.log(title2);
// console.log(topla(5,4));
// console.log(cikart(5,4));
// // console.log(hello());
// console.log(helloname("Alper"));
// // console.log(text);
// // console.log(user);
// // console.log(user.name);
// console.log(array_users[0].name);
